//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantType
    {
        public ApplicantType()
        {
            this.ApplicantProfiles = new HashSet<ApplicantProfile>();
            this.Deadlines = new HashSet<Deadline>();
            this.MemberFees = new HashSet<MemberFee>();
        }
    
        public short ApplicantTypeId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual ICollection<ApplicantProfile> ApplicantProfiles { get; set; }
        public virtual ICollection<Deadline> Deadlines { get; set; }
        public virtual ICollection<MemberFee> MemberFees { get; set; }
    }
}
