//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantMember
    {
        public ApplicantMember()
        {
            this.ApplicantForms = new HashSet<ApplicantForm>();
            this.MemberAnswers = new HashSet<MemberAnswer>();
            this.Payments = new HashSet<Payment>();
        }
    
        public decimal ApplicantMemberId { get; set; }
        public decimal ApplicantId { get; set; }
        public decimal MemberId { get; set; }
        public Nullable<short> TermId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> DecisionTypeId { get; set; }
        public Nullable<int> ArtsSupp { get; set; }
        public Nullable<sbyte> RefreshScreen { get; set; }
    
        public virtual ICollection<ApplicantForm> ApplicantForms { get; set; }
        public virtual ApplicantProfile ApplicantProfile { get; set; }
        public virtual DecisionType DecisionType { get; set; }
        public virtual Member Member { get; set; }
        public virtual Term Term { get; set; }
        public virtual ICollection<MemberAnswer> MemberAnswers { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
