//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantForm
    {
        public decimal ApplicantFormId { get; set; }
        public decimal ApplicantMemberId { get; set; }
        public decimal ApplicantId { get; set; }
        public decimal FormId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<System.DateTime> ApprovedSubmissionDate { get; set; }
        public bool SubmissionApproved { get; set; }
        public Nullable<System.DateTime> ProspectExportedDate { get; set; }
        public Nullable<System.DateTime> SuspectExportedDate { get; set; }
    
        public virtual ApplicantMember ApplicantMember { get; set; }
        public virtual Form Form { get; set; }
    }
}
