//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceGrpReqRule
    {
        public ChoiceGrpReqRule()
        {
            this.ChoiceGrpRuleTriggers = new HashSet<ChoiceGrpRuleTrigger>();
        }
    
        public long ChoiceGrpReqRuleId { get; set; }
        public decimal ReqGroupId { get; set; }
        public decimal Trigger1QuestionId { get; set; }
        public Nullable<decimal> Trigger2QuestionId { get; set; }
        public Nullable<decimal> Trigger3QuestionId { get; set; }
        public Nullable<decimal> Trigger4QuestionId { get; set; }
        public Nullable<decimal> Trigger5QuestionId { get; set; }
        public Nullable<bool> NewRequired { get; set; }
        public Nullable<bool> NewIgnored { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string ChoiceGrpReqRuleName { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual Question Question2 { get; set; }
        public virtual Question Question3 { get; set; }
        public virtual Question Question4 { get; set; }
        public virtual ReqGroup ReqGroup { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers { get; set; }
    }
}
