//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportTemplate
    {
        public ExportTemplate()
        {
            this.ExportTemplateFields = new HashSet<ExportTemplateField>();
            this.SDSConfigs = new HashSet<SDSConfig>();
        }
    
        public int ExportTemplateId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public short ExportFileTypeId { get; set; }
        public string Delimiter { get; set; }
        public Nullable<bool> QuotedString { get; set; }
        public Nullable<short> LineDelimiter { get; set; }
        public int ExportTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> GlobalExportTemplateId { get; set; }
    
        public virtual ExportFileType ExportFileType { get; set; }
        public virtual ExportType ExportType { get; set; }
        public virtual ICollection<ExportTemplateField> ExportTemplateFields { get; set; }
        public virtual ICollection<SDSConfig> SDSConfigs { get; set; }
    }
}
