//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolLookup
    {
        public int HighSchoolLookupId { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string CountryCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public string SchoolTypeCode { get; set; }
        public string StatusChangeCode { get; set; }
        public Nullable<sbyte> RecSource { get; set; }
        public string QasAddressVerifyLevel { get; set; }
        public Nullable<bool> IsModified { get; set; }
    }
}
