//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public Invitation()
        {
            this.InvitationEmailRequests = new HashSet<InvitationEmailRequest>();
            this.RecAssignments = new HashSet<RecAssignment>();
            this.RecForms = new HashSet<RecForm>();
        }
    
        public decimal InvitationId { get; set; }
        public decimal RecommenderId { get; set; }
        public decimal ApplicantId { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public int RecPersonaTypeId { get; set; }
        public Nullable<sbyte> RecSource { get; set; }
        public Nullable<System.DateTime> StatusUpdatedDate { get; set; }
        public Nullable<int> RecPersonaSubTypeId { get; set; }
        public Nullable<sbyte> Decline { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string RefreshComScreen { get; set; }
    
        public virtual ApplicantProfile ApplicantProfile { get; set; }
        public virtual RecPersonaType RecPersonaType { get; set; }
        public virtual ICollection<InvitationEmailRequest> InvitationEmailRequests { get; set; }
        public virtual ICollection<RecAssignment> RecAssignments { get; set; }
        public virtual ICollection<RecForm> RecForms { get; set; }
    }
}
