//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReqGroupTemplate
    {
        public MemberReqGroupTemplate()
        {
            this.MemberAddAnotherGrpItemDetTemplates = new HashSet<MemberAddAnotherGrpItemDetTemplate>();
            this.MemberReqGroupDetailTemplates = new HashSet<MemberReqGroupDetailTemplate>();
            this.ReqGroups = new HashSet<ReqGroup>();
        }
    
        public int MemberReqGroupTemplateId { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> DefaultRequired { get; set; }
        public Nullable<bool> DefaultIgnored { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<MemberAddAnotherGrpItemDetTemplate> MemberAddAnotherGrpItemDetTemplates { get; set; }
        public virtual ICollection<MemberReqGroupDetailTemplate> MemberReqGroupDetailTemplates { get; set; }
        public virtual ICollection<ReqGroup> ReqGroups { get; set; }
    }
}
