//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReqRuleTrgrTemplate
    {
        public MemberReqRuleTrgrTemplate()
        {
            this.ReqRuleTriggers = new HashSet<ReqRuleTrigger>();
        }
    
        public int MemberReqRuleTrgrTemplateId { get; set; }
        public int MemberReqRuleTemplateId { get; set; }
        public int MemberTriggerQuestionTemplateId { get; set; }
        public Nullable<int> MemberTargetSectionTemplateId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual MemberQuestionTemplate MemberQuestionTemplate { get; set; }
        public virtual MemberReqRuleTemplate MemberReqRuleTemplate { get; set; }
        public virtual MemberSectionTemplate MemberSectionTemplate { get; set; }
        public virtual ICollection<ReqRuleTrigger> ReqRuleTriggers { get; set; }
    }
}
