//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSectionTemplate
    {
        public MemberSectionTemplate()
        {
            this.MemberAddAnotherGrpTemplates = new HashSet<MemberAddAnotherGrpTemplate>();
            this.MemberQuestionTemplates = new HashSet<MemberQuestionTemplate>();
            this.MemberReqRuleTrgrTemplates = new HashSet<MemberReqRuleTrgrTemplate>();
            this.Sections = new HashSet<Section>();
        }
    
        public int MemberSectionTemplateId { get; set; }
        public int MemberScreenTemplateId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> AddAnother { get; set; }
    
        public virtual ICollection<MemberAddAnotherGrpTemplate> MemberAddAnotherGrpTemplates { get; set; }
        public virtual ICollection<MemberQuestionTemplate> MemberQuestionTemplates { get; set; }
        public virtual ICollection<MemberReqRuleTrgrTemplate> MemberReqRuleTrgrTemplates { get; set; }
        public virtual MemberScreenTemplate MemberScreenTemplate { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
