//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberValGroupTemplate
    {
        public MemberValGroupTemplate()
        {
            this.MemberValGroupDetailTemplates = new HashSet<MemberValGroupDetailTemplate>();
            this.ValGroups = new HashSet<ValGroup>();
        }
    
        public int MemberValGroupTemplateId { get; set; }
        public string Name { get; set; }
        public string ValType { get; set; }
        public string RelOperator { get; set; }
        public string Value { get; set; }
        public Nullable<short> NValue { get; set; }
        public bool DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public string ErrMessage { get; set; }
    
        public virtual ICollection<MemberValGroupDetailTemplate> MemberValGroupDetailTemplates { get; set; }
        public virtual ICollection<ValGroup> ValGroups { get; set; }
    }
}
