//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberKeyfact
    {
        public int MemberKeyfactsId { get; set; }
        public int scid { get; set; }
        public decimal MemberId { get; set; }
        public string CampusName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public bool DeleteStatus { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
