//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberQuestionTemplate
    {
        public MemberQuestionTemplate()
        {
            this.ExportTemplateFields = new HashSet<ExportTemplateField>();
            this.MemberReqGroupDetailTemplates = new HashSet<MemberReqGroupDetailTemplate>();
            this.MemberReqRuleExpTemplates = new HashSet<MemberReqRuleExpTemplate>();
            this.MemberReqRuleTrgrTemplates = new HashSet<MemberReqRuleTrgrTemplate>();
            this.MemberValGroupDetailTemplates = new HashSet<MemberValGroupDetailTemplate>();
            this.Questions = new HashSet<Question>();
        }
    
        public int MemberQuestionTemplateId { get; set; }
        public int MemberSectionTemplateId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public int QuestionTypeId { get; set; }
        public Nullable<decimal> ChoiceGroupId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string ComplianceLabel { get; set; }
        public string Min { get; set; }
        public string Max { get; set; }
        public string ParseToDataType { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public bool IsExtnDisplayed { get; set; }
        public string PlaceholderText { get; set; }
        public string MaskInputPattern { get; set; }
        public string ValidationPattern { get; set; }
        public string AllowedCharacters { get; set; }
        public string AutoformatPattern { get; set; }
        public string ErrorMessage { get; set; }
        public short OrderSeq { get; set; }
        public bool IsCustomValidate { get; set; }
        public bool IsDynamicChoiceImpact { get; set; }
        public bool IsDynamicChoiceTrigger { get; set; }
        public Nullable<bool> AlwaysAsked { get; set; }
        public Nullable<bool> CustomLabel { get; set; }
        public Nullable<bool> CustomChoiceGrp { get; set; }
    
        public virtual ChoiceGroup ChoiceGroup { get; set; }
        public virtual ICollection<ExportTemplateField> ExportTemplateFields { get; set; }
        public virtual ICollection<MemberReqGroupDetailTemplate> MemberReqGroupDetailTemplates { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual MemberSectionTemplate MemberSectionTemplate { get; set; }
        public virtual ICollection<MemberReqRuleExpTemplate> MemberReqRuleExpTemplates { get; set; }
        public virtual ICollection<MemberReqRuleTrgrTemplate> MemberReqRuleTrgrTemplates { get; set; }
        public virtual ICollection<MemberValGroupDetailTemplate> MemberValGroupDetailTemplates { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
