//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddAnotherGrpItemDetTemplate
    {
        public MemberAddAnotherGrpItemDetTemplate()
        {
            this.AddAnotherGrpItemDetails = new HashSet<AddAnotherGrpItemDetail>();
        }
    
        public int MemberAAGrpItemDetTemplateId { get; set; }
        public int MemberAAGrpItemTemplateId { get; set; }
        public int MemberReqGroupTemplateId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<AddAnotherGrpItemDetail> AddAnotherGrpItemDetails { get; set; }
        public virtual MemberAddAnotherGrpItemTemplate MemberAddAnotherGrpItemTemplate { get; set; }
        public virtual MemberReqGroupTemplate MemberReqGroupTemplate { get; set; }
    }
}
