//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentEDAnswer
    {
        public long ParentEDAnswerId { get; set; }
        public Nullable<decimal> InvitationId { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public string ParentSign { get; set; }
        public Nullable<System.DateTime> ParentSignDate { get; set; }
        public Nullable<bool> ParentAffir { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
