//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PmtReconciliation
    {
        public PmtReconciliation()
        {
            this.PmtReconciliationDetails = new HashSet<PmtReconciliationDetail>();
        }
    
        public int PmtReconciliationId { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public Nullable<int> NoOfRecordInFile { get; set; }
        public Nullable<int> MatchedCount { get; set; }
        public Nullable<int> NotmatchedCount { get; set; }
        public Nullable<int> Epaymentvendortypeid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual ICollection<PmtReconciliationDetail> PmtReconciliationDetails { get; set; }
    }
}
