//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilege
    {
        public Privilege()
        {
            this.RolePrivileges = new HashSet<RolePrivilege>();
            this.SeasonPrivileges = new HashSet<SeasonPrivilege>();
        }
    
        public int PrivilegeId { get; set; }
        public string PrivilegeName { get; set; }
        public string Description { get; set; }
        public string PrivilegeGroupName { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual UserType UserType { get; set; }
        public virtual ICollection<RolePrivilege> RolePrivileges { get; set; }
        public virtual ICollection<SeasonPrivilege> SeasonPrivileges { get; set; }
    }
}
