//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecPersonaType
    {
        public RecPersonaType()
        {
            this.Invitations = new HashSet<Invitation>();
        }
    
        public int RecPersonaTypeId { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public Nullable<sbyte> Source { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
    
        public virtual ICollection<Invitation> Invitations { get; set; }
    }
}
