//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecSummaryHistory
    {
        public long RecPackageSummaryId { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<int> RecPersonaTypeId { get; set; }
        public Nullable<long> FormId { get; set; }
        public Nullable<sbyte> RecSource { get; set; }
        public decimal COUNTS { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<System.DateTime> RUNDate { get; set; }
        public Nullable<short> ApplicantTypeId { get; set; }
        public Nullable<short> ReportType { get; set; }
    }
}
