//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqGroup
    {
        public ReqGroup()
        {
            this.AddAnotherGrpItemDetails = new HashSet<AddAnotherGrpItemDetail>();
            this.ChoiceGrpReqRules = new HashSet<ChoiceGrpReqRule>();
            this.ReqGroupDetails = new HashSet<ReqGroupDetail>();
            this.ReqRules = new HashSet<ReqRule>();
        }
    
        public decimal ReqGroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public bool DefaultRequired { get; set; }
        public bool DefaultIgnored { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<int> MemberReqGroupTemplateId { get; set; }
    
        public virtual ICollection<AddAnotherGrpItemDetail> AddAnotherGrpItemDetails { get; set; }
        public virtual ICollection<ChoiceGrpReqRule> ChoiceGrpReqRules { get; set; }
        public virtual Member Member { get; set; }
        public virtual MemberReqGroupTemplate MemberReqGroupTemplate { get; set; }
        public virtual ICollection<ReqGroupDetail> ReqGroupDetails { get; set; }
        public virtual ICollection<ReqRule> ReqRules { get; set; }
    }
}
