//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqRule
    {
        public ReqRule()
        {
            this.ReqRuleExpressions = new HashSet<ReqRuleExpression>();
            this.ReqRuleTriggers = new HashSet<ReqRuleTrigger>();
        }
    
        public decimal ReqRuleId { get; set; }
        public decimal ReqGroupId { get; set; }
        public Nullable<bool> NewRequired { get; set; }
        public Nullable<bool> NewIgnored { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string LogicalOperator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string ReqRuleName { get; set; }
        public Nullable<int> MemberReqRuleTemplateId { get; set; }
    
        public virtual MemberReqRuleTemplate MemberReqRuleTemplate { get; set; }
        public virtual ReqGroup ReqGroup { get; set; }
        public virtual ICollection<ReqRuleExpression> ReqRuleExpressions { get; set; }
        public virtual ICollection<ReqRuleTrigger> ReqRuleTriggers { get; set; }
    }
}
