//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenType
    {
        public ScreenType()
        {
            this.Screens = new HashSet<Screen>();
        }
    
        public int ScreenTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual ICollection<Screen> Screens { get; set; }
    }
}
