//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.AddAnotherGrps = new HashSet<AddAnotherGrp>();
            this.Questions = new HashSet<Question>();
        }
    
        public decimal SectionId { get; set; }
        public decimal ScreenId { get; set; }
        public string Name { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public string Label { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public sbyte AddAnother { get; set; }
        public Nullable<int> MemberSectionTemplateId { get; set; }
        public Nullable<bool> HelpTopic { get; set; }
    
        public virtual ICollection<AddAnotherGrp> AddAnotherGrps { get; set; }
        public virtual MemberSectionTemplate MemberSectionTemplate { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
