//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemField
    {
        public int SystemFieldsId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExportTypeId { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual ExportType ExportType { get; set; }
    }
}
