//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.ApplicantMembers = new HashSet<ApplicantMember>();
            this.Deadlines = new HashSet<Deadline>();
        }
    
        public short TermId { get; set; }
        public decimal MemberId { get; set; }
        public string Term1 { get; set; }
        public Nullable<sbyte> OrderSeq { get; set; }
        public short TermTypeId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual ICollection<ApplicantMember> ApplicantMembers { get; set; }
        public virtual ICollection<Deadline> Deadlines { get; set; }
        public virtual Member Member { get; set; }
    }
}
