//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int UserProfileId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool ActiveUser { get; set; }
        public bool Locked { get; set; }
        public bool DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public decimal MemberId { get; set; }
        public string Email { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
