//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonAppPoco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValGroup
    {
        public ValGroup()
        {
            this.ValGroupDetails = new HashSet<ValGroupDetail>();
        }
    
        public decimal ValGroupId { get; set; }
        public string Name { get; set; }
        public string ValType { get; set; }
        public string RelOperator { get; set; }
        public string Value { get; set; }
        public Nullable<short> NValue { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public bool DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string ErrMessage { get; set; }
        public Nullable<int> MemberValGroupTemplateId { get; set; }
        public bool GroupValidIfAnyAnswerIsNull { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MemberValGroupTemplate MemberValGroupTemplate { get; set; }
        public virtual ICollection<ValGroupDetail> ValGroupDetails { get; set; }
    }
}
