//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDataFirstConsole.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public userdetail()
        {
            this.userdatas = new HashSet<userdata>();
        }
    
        public int UserDetailsId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<userdata> userdatas { get; set; }
    }
}
