//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantProfile
    {
        public ApplicantProfile()
        {
            this.ApplicantMembers = new HashSet<ApplicantMember>();
            this.CommonAnswers = new HashSet<CommonAnswer>();
            this.Invitations = new HashSet<Invitation>();
            this.MemberAnswers = new HashSet<MemberAnswer>();
            this.RecForms = new HashSet<RecForm>();
        }
    
        public decimal ApplicantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string CountryCode { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<short> ApplicantTypeId { get; set; }
        public Nullable<short> ResidencyTypeId { get; set; }
        public Nullable<sbyte> RecView { get; set; }
        public Nullable<sbyte> RegistrationType { get; set; }
        public Nullable<bool> CommunicationOption { get; set; }
        public Nullable<int> FirstGeneration { get; set; }
        public Nullable<int> SchoolTypeCode { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<bool> IsFerpaWaived { get; set; }
        public string FerpaSign { get; set; }
        public Nullable<System.DateTime> FerpaDate { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Email { get; set; }
        public Nullable<sbyte> TestApp { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string ComRefreshScreen { get; set; }
        public Nullable<bool> IsWritingSupSectionEdited { get; set; }
        public Nullable<short> WritingSupSubCnt { get; set; }
        public Nullable<int> IsCAFeeWaiverRequired { get; set; }
    
        public virtual ICollection<ApplicantMember> ApplicantMembers { get; set; }
        public virtual ApplicantType ApplicantType { get; set; }
        public virtual ResidencyType ResidencyType { get; set; }
        public virtual ICollection<CommonAnswer> CommonAnswers { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<MemberAnswer> MemberAnswers { get; set; }
        public virtual ICollection<RecForm> RecForms { get; set; }
    }
}
