//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceValue
    {
        public ChoiceValue()
        {
            this.ChoiceGrpRuleImpacts = new HashSet<ChoiceGrpRuleImpact>();
            this.ChoiceGrpRuleTriggers = new HashSet<ChoiceGrpRuleTrigger>();
            this.ChoiceGrpRuleTriggers1 = new HashSet<ChoiceGrpRuleTrigger>();
            this.ChoiceGrpRuleTriggers2 = new HashSet<ChoiceGrpRuleTrigger>();
            this.ChoiceGrpRuleTriggers3 = new HashSet<ChoiceGrpRuleTrigger>();
            this.ChoiceGrpRuleTriggers4 = new HashSet<ChoiceGrpRuleTrigger>();
        }
    
        public decimal ChoiceValueId { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public string ChoiceLabel { get; set; }
        public string ChoiceValue1 { get; set; }
        public decimal ChoiceGroupid { get; set; }
        public string ExportCode { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string MemberExportCode { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual ChoiceGroup ChoiceGroup { get; set; }
        public virtual ICollection<ChoiceGrpRuleImpact> ChoiceGrpRuleImpacts { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers1 { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers2 { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers3 { get; set; }
        public virtual ICollection<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers4 { get; set; }
    }
}
