//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoiceGrpRuleTrigger
    {
        public ChoiceGrpRuleTrigger()
        {
            this.ChoiceGrpRuleImpacts = new HashSet<ChoiceGrpRuleImpact>();
        }
    
        public long ChoiceGrpRuleTriggerId { get; set; }
        public long ChoiceGrpReqRuleId { get; set; }
        public decimal Trigger1ChoiceValueId { get; set; }
        public Nullable<decimal> Trigger2ChoiceValueId { get; set; }
        public Nullable<decimal> Trigger3ChoiceValueId { get; set; }
        public Nullable<decimal> Trigger4ChoiceValueId { get; set; }
        public Nullable<decimal> Trigger5ChoiceValueId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string ChoiceGrpRuleTriggerName { get; set; }
    
        public virtual ChoiceGrpReqRule ChoiceGrpReqRule { get; set; }
        public virtual ICollection<ChoiceGrpRuleImpact> ChoiceGrpRuleImpacts { get; set; }
        public virtual ChoiceValue ChoiceValue { get; set; }
        public virtual ChoiceValue ChoiceValue1 { get; set; }
        public virtual ChoiceValue ChoiceValue2 { get; set; }
        public virtual ChoiceValue ChoiceValue3 { get; set; }
        public virtual ChoiceValue ChoiceValue4 { get; set; }
    }
}
