//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using CommonAppPoco.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CACloud14Entities : DbContext
    {
        public CACloud14Entities()
            : base("name=CACloud14Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddAnotherGrp> AddAnotherGrps { get; set; }
        public virtual DbSet<AddAnotherGrpItem> AddAnotherGrpItems { get; set; }
        public virtual DbSet<AddAnotherGrpItemDetail> AddAnotherGrpItemDetails { get; set; }
        public virtual DbSet<ApplicantForm> ApplicantForms { get; set; }
        public virtual DbSet<ApplicantMember> ApplicantMembers { get; set; }
        public virtual DbSet<ApplicantProfile> ApplicantProfiles { get; set; }
        public virtual DbSet<ApplicantType> ApplicantTypes { get; set; }
        public virtual DbSet<ChoiceGroup> ChoiceGroups { get; set; }
        public virtual DbSet<ChoiceGrpReqRule> ChoiceGrpReqRules { get; set; }
        public virtual DbSet<ChoiceGrpRuleImpact> ChoiceGrpRuleImpacts { get; set; }
        public virtual DbSet<ChoiceGrpRuleTrigger> ChoiceGrpRuleTriggers { get; set; }
        public virtual DbSet<ChoiceValue> ChoiceValues { get; set; }
        public virtual DbSet<CollegeLookup> CollegeLookups { get; set; }
        public virtual DbSet<CommonAnswer> CommonAnswers { get; set; }
        public virtual DbSet<Deadline> Deadlines { get; set; }
        public virtual DbSet<DeadlineType> DeadlineTypes { get; set; }
        public virtual DbSet<DecisionType> DecisionTypes { get; set; }
        public virtual DbSet<DownloadDataHistory> DownloadDataHistories { get; set; }
        public virtual DbSet<ExportFileType> ExportFileTypes { get; set; }
        public virtual DbSet<ExportTemplate> ExportTemplates { get; set; }
        public virtual DbSet<ExportTemplateField> ExportTemplateFields { get; set; }
        public virtual DbSet<ExportType> ExportTypes { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<HighSchoolLookup> HighSchoolLookups { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<InvitationEmailRequest> InvitationEmailRequests { get; set; }
        public virtual DbSet<KeyfactsXMLData> KeyfactsXMLDatas { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberAddAnotherGrpItemDetTemplate> MemberAddAnotherGrpItemDetTemplates { get; set; }
        public virtual DbSet<MemberAddAnotherGrpItemTemplate> MemberAddAnotherGrpItemTemplates { get; set; }
        public virtual DbSet<MemberAddAnotherGrpTemplate> MemberAddAnotherGrpTemplates { get; set; }
        public virtual DbSet<MemberAnswer> MemberAnswers { get; set; }
        public virtual DbSet<MemberFee> MemberFees { get; set; }
        public virtual DbSet<MemberKeyfact> MemberKeyfacts { get; set; }
        public virtual DbSet<MemberPaymentConfig> MemberPaymentConfigs { get; set; }
        public virtual DbSet<MemberQuestionTemplate> MemberQuestionTemplates { get; set; }
        public virtual DbSet<MemberRecPersonaSubType> MemberRecPersonaSubTypes { get; set; }
        public virtual DbSet<MemberReqGroupDetailTemplate> MemberReqGroupDetailTemplates { get; set; }
        public virtual DbSet<MemberReqGroupTemplate> MemberReqGroupTemplates { get; set; }
        public virtual DbSet<MemberReqRuleExpTemplate> MemberReqRuleExpTemplates { get; set; }
        public virtual DbSet<MemberReqRuleTemplate> MemberReqRuleTemplates { get; set; }
        public virtual DbSet<MemberReqRuleTrgrTemplate> MemberReqRuleTrgrTemplates { get; set; }
        public virtual DbSet<MemberScreenTemplate> MemberScreenTemplates { get; set; }
        public virtual DbSet<MemberSectionTemplate> MemberSectionTemplates { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<MemberValGroupDetailTemplate> MemberValGroupDetailTemplates { get; set; }
        public virtual DbSet<MemberValGroupTemplate> MemberValGroupTemplates { get; set; }
        public virtual DbSet<MetricsSummaryDaily> MetricsSummaryDailies { get; set; }
        public virtual DbSet<MetricsSummaryHistory> MetricsSummaryHistories { get; set; }
        public virtual DbSet<ParentEDAnswer> ParentEDAnswers { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentRequest> PaymentRequests { get; set; }
        public virtual DbSet<PaymentResponse> PaymentResponses { get; set; }
        public virtual DbSet<PdfReGenQueue> PdfReGenQueues { get; set; }
        public virtual DbSet<PmtReconciliation> PmtReconciliations { get; set; }
        public virtual DbSet<PmtReconciliationDetail> PmtReconciliationDetails { get; set; }
        public virtual DbSet<PoolStageCode> PoolStageCodes { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<RecAssignment> RecAssignments { get; set; }
        public virtual DbSet<RecForm> RecForms { get; set; }
        public virtual DbSet<RecFormAnswer> RecFormAnswers { get; set; }
        public virtual DbSet<RecPersonaSubType> RecPersonaSubTypes { get; set; }
        public virtual DbSet<RecPersonaType> RecPersonaTypes { get; set; }
        public virtual DbSet<RecProfile> RecProfiles { get; set; }
        public virtual DbSet<RecProfileAnswer> RecProfileAnswers { get; set; }
        public virtual DbSet<RecSummaryHistory> RecSummaryHistories { get; set; }
        public virtual DbSet<ReqGroup> ReqGroups { get; set; }
        public virtual DbSet<ReqGroupDetail> ReqGroupDetails { get; set; }
        public virtual DbSet<ReqRule> ReqRules { get; set; }
        public virtual DbSet<ReqRuleExpression> ReqRuleExpressions { get; set; }
        public virtual DbSet<ReqRuleTrigger> ReqRuleTriggers { get; set; }
        public virtual DbSet<ResidencyType> ResidencyTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleMember> RoleMembers { get; set; }
        public virtual DbSet<RolePrivilege> RolePrivileges { get; set; }
        public virtual DbSet<Screen> Screens { get; set; }
        public virtual DbSet<ScreenType> ScreenTypes { get; set; }
        public virtual DbSet<SDSConfig> SDSConfigs { get; set; }
        public virtual DbSet<SDSSchedule> SDSSchedules { get; set; }
        public virtual DbSet<SeasonPrivilege> SeasonPrivileges { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SessionLog> SessionLogs { get; set; }
        public virtual DbSet<SubmittedAnswers1> SubmittedAnswers1 { get; set; }
        public virtual DbSet<SubmittedAnswers10> SubmittedAnswers10 { get; set; }
        public virtual DbSet<SubmittedAnswers11> SubmittedAnswers11 { get; set; }
        public virtual DbSet<SubmittedAnswers12> SubmittedAnswers12 { get; set; }
        public virtual DbSet<SubmittedAnswers13> SubmittedAnswers13 { get; set; }
        public virtual DbSet<SubmittedAnswers14> SubmittedAnswers14 { get; set; }
        public virtual DbSet<SubmittedAnswers15> SubmittedAnswers15 { get; set; }
        public virtual DbSet<SubmittedAnswers2> SubmittedAnswers2 { get; set; }
        public virtual DbSet<SubmittedAnswers3> SubmittedAnswers3 { get; set; }
        public virtual DbSet<SubmittedAnswers4> SubmittedAnswers4 { get; set; }
        public virtual DbSet<SubmittedAnswers5> SubmittedAnswers5 { get; set; }
        public virtual DbSet<SubmittedAnswers6> SubmittedAnswers6 { get; set; }
        public virtual DbSet<SubmittedAnswers7> SubmittedAnswers7 { get; set; }
        public virtual DbSet<SubmittedAnswers8> SubmittedAnswers8 { get; set; }
        public virtual DbSet<SubmittedAnswers9> SubmittedAnswers9 { get; set; }
        public virtual DbSet<SubmittedAnswersMemberBucket> SubmittedAnswersMemberBuckets { get; set; }
        public virtual DbSet<SuppressionGroup> SuppressionGroups { get; set; }
        public virtual DbSet<SuppressionGroupDetail> SuppressionGroupDetails { get; set; }
        public virtual DbSet<SupressionMemberConfig> SupressionMemberConfigs { get; set; }
        public virtual DbSet<SystemField> SystemFields { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<TermType> TermTypes { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<ValGroup> ValGroups { get; set; }
        public virtual DbSet<ValGroupDetail> ValGroupDetails { get; set; }
        public virtual DbSet<ZIPCode> ZIPCodes { get; set; }
    }
}
