//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deadline
    {
        public int DeadlineId { get; set; }
        public string Name { get; set; }
        public System.DateTime DeadlineDate { get; set; }
        public int DeadlineTypeId { get; set; }
        public short ApplicantTypeId { get; set; }
        public int DecisionTypeId { get; set; }
        public short TermId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual ApplicantType ApplicantType { get; set; }
        public virtual DeadlineType DeadlineType { get; set; }
        public virtual DecisionType DecisionType { get; set; }
        public virtual Term Term { get; set; }
    }
}
