//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadDataHistory
    {
        public int DownloadDataHistoryId { get; set; }
        public decimal MemberId { get; set; }
        public Nullable<short> ScheduleType { get; set; }
        public Nullable<short> ProcessType { get; set; }
        public int UserProfileId { get; set; }
        public int RecordsCount { get; set; }
        public string FileName { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
