//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportTemplateField
    {
        public int ExportTemplateFieldId { get; set; }
        public int ExportTemplateId { get; set; }
        public long QuestionId { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public Nullable<int> OrderSeq { get; set; }
        public Nullable<int> FieldStart { get; set; }
        public Nullable<int> FieldEnd { get; set; }
        public string FieldLiteral { get; set; }
        public string LiteralType { get; set; }
        public Nullable<bool> UseCode { get; set; }
        public string XmlTag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> MemberQuestionTemplateId { get; set; }
        public Nullable<short> QuestionSubTypeId { get; set; }
        public Nullable<bool> NumericOnly { get; set; }
    
        public virtual ExportTemplate ExportTemplate { get; set; }
        public virtual MemberQuestionTemplate MemberQuestionTemplate { get; set; }
    }
}
