//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.ApplicantForms = new HashSet<ApplicantForm>();
            this.RecForms = new HashSet<RecForm>();
            this.RecFormAnswers = new HashSet<RecFormAnswer>();
            this.Screens = new HashSet<Screen>();
        }
    
        public decimal FormId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<int> FormTypeId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<bool> FY { get; set; }
        public Nullable<bool> TR { get; set; }
    
        public virtual ICollection<ApplicantForm> ApplicantForms { get; set; }
        public virtual ICollection<RecForm> RecForms { get; set; }
        public virtual ICollection<RecFormAnswer> RecFormAnswers { get; set; }
        public virtual ICollection<Screen> Screens { get; set; }
    }
}
