//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddAnotherGrpItemTemplate
    {
        public MemberAddAnotherGrpItemTemplate()
        {
            this.AddAnotherGrpItems = new HashSet<AddAnotherGrpItem>();
            this.MemberAddAnotherGrpItemDetTemplates = new HashSet<MemberAddAnotherGrpItemDetTemplate>();
        }
    
        public int MemberAAGrpItemTemplateId { get; set; }
        public string ItemName { get; set; }
        public int MemberAAGrpTemplateId { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<AddAnotherGrpItem> AddAnotherGrpItems { get; set; }
        public virtual ICollection<MemberAddAnotherGrpItemDetTemplate> MemberAddAnotherGrpItemDetTemplates { get; set; }
        public virtual MemberAddAnotherGrpTemplate MemberAddAnotherGrpTemplate { get; set; }
    }
}
