//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAddAnotherGrpTemplate
    {
        public MemberAddAnotherGrpTemplate()
        {
            this.AddAnotherGrps = new HashSet<AddAnotherGrp>();
            this.MemberAddAnotherGrpItemTemplates = new HashSet<MemberAddAnotherGrpItemTemplate>();
        }
    
        public int MemberAAGrpTemplateId { get; set; }
        public string Name { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> MemberSectionTemplateId { get; set; }
    
        public virtual ICollection<AddAnotherGrp> AddAnotherGrps { get; set; }
        public virtual ICollection<MemberAddAnotherGrpItemTemplate> MemberAddAnotherGrpItemTemplates { get; set; }
        public virtual MemberSectionTemplate MemberSectionTemplate { get; set; }
    }
}
