//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFee
    {
        public int MemberFeeId { get; set; }
        public int MemberId { get; set; }
        public Nullable<short> ApplicantTypeId { get; set; }
        public Nullable<short> ResidencyTypeId { get; set; }
        public Nullable<double> FeeAmount { get; set; }
        public string FeeLabel { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> PaymentType { get; set; }
    
        public virtual ApplicantType ApplicantType { get; set; }
        public virtual ResidencyType ResidencyType { get; set; }
    }
}
