//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberScreenTemplate
    {
        public MemberScreenTemplate()
        {
            this.MemberSectionTemplates = new HashSet<MemberSectionTemplate>();
            this.Screens = new HashSet<Screen>();
        }
    
        public int MemberScreenTemplateId { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<short> OrderSeq { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<MemberSectionTemplate> MemberSectionTemplates { get; set; }
        public virtual ICollection<Screen> Screens { get; set; }
    }
}
