//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReqRuleExpTemplate
    {
        public MemberReqRuleExpTemplate()
        {
            this.ReqRuleExpressions = new HashSet<ReqRuleExpression>();
        }
    
        public int MemberReqRuleExpTemplateId { get; set; }
        public int MemberReqRuleTemplateId { get; set; }
        public string RelationalOperator { get; set; }
        public int MemberQuestionTemplateId { get; set; }
        public string Response { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual MemberQuestionTemplate MemberQuestionTemplate { get; set; }
        public virtual MemberReqRuleTemplate MemberReqRuleTemplate { get; set; }
        public virtual ICollection<ReqRuleExpression> ReqRuleExpressions { get; set; }
    }
}
