//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReqRuleTemplate
    {
        public MemberReqRuleTemplate()
        {
            this.MemberReqRuleExpTemplates = new HashSet<MemberReqRuleExpTemplate>();
            this.MemberReqRuleTrgrTemplates = new HashSet<MemberReqRuleTrgrTemplate>();
            this.ReqRules = new HashSet<ReqRule>();
        }
    
        public int MemberReqRuleTemplateId { get; set; }
        public int MemberReqGroupTemplateId { get; set; }
        public Nullable<bool> NewRequired { get; set; }
        public Nullable<bool> NewIgnored { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string LogicalOperator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public string ReqRuleName { get; set; }
    
        public virtual ICollection<MemberReqRuleExpTemplate> MemberReqRuleExpTemplates { get; set; }
        public virtual ICollection<MemberReqRuleTrgrTemplate> MemberReqRuleTrgrTemplates { get; set; }
        public virtual ICollection<ReqRule> ReqRules { get; set; }
    }
}
