//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPaymentConfig
    {
        public MemberPaymentConfig()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int MemberPaymentConfigId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentPkgId { get; set; }
        public string RedirectURL { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
    }
}
