//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricsSummaryHistory
    {
        public long PackageSummaryId { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public Nullable<short> ApplicantTypeId { get; set; }
        public Nullable<short> TermId { get; set; }
        public Nullable<int> DecisionTypeId { get; set; }
        public string State { get; set; }
        public string CountryCode { get; set; }
        public string Gender { get; set; }
        public Nullable<short> ResidencyTypeId { get; set; }
        public Nullable<int> FirstGeneration { get; set; }
        public Nullable<int> ReportTypeId { get; set; }
        public Nullable<long> TermTypeId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public Nullable<System.DateTime> RUNDate { get; set; }
        public decimal COUNTS { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    }
}
