//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<short> PaymentType { get; set; }
        public Nullable<double> Amount { get; set; }
        public string TransactionCode { get; set; }
        public string OrderId { get; set; }
        public string AuthenticationCode { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<short> ElapsedSeconds { get; set; }
        public Nullable<int> EPaymentVendorId { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<decimal> ApplicantMemberId { get; set; }
        public string Guid { get; set; }
    
        public virtual ApplicantMember ApplicantMember { get; set; }
    }
}
