//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        public int PaymentRequestID { get; set; }
        public string ActionPage { get; set; }
        public Nullable<int> PaymentPkgId { get; set; }
        public string OrderId { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<System.DateTime> RRDateTime { get; set; }
        public Nullable<int> ApplicantMemberId { get; set; }
        public string PaymentIndicator { get; set; }
        public string ReturnUrl { get; set; }
        public string CancelUrl { get; set; }
        public string PostbackUrl { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string HostName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    }
}
