//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PdfReGenQueue
    {
        public long PdfReGenQueueId { get; set; }
        public Nullable<long> ApplicantId { get; set; }
        public long MemberId { get; set; }
        public long FormId { get; set; }
        public Nullable<long> InvitationId { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public string StatusMessage { get; set; }
    }
}
