//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionType
    {
        public QuestionType()
        {
            this.MemberQuestionTemplates = new HashSet<MemberQuestionTemplate>();
            this.Questions = new HashSet<Question>();
        }
    
        public int QuestionTypeId { get; set; }
        public string QuestionTypeName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool DeleteStatus { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual ICollection<MemberQuestionTemplate> MemberQuestionTemplates { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
