//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecFormAnswer
    {
        public decimal RecFormAnswerId { get; set; }
        public decimal InvitationId { get; set; }
        public decimal QuestionId { get; set; }
        public string Response { get; set; }
        public string Contenttype { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string CountryCode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string VerifyLevel { get; set; }
        public string CEEBCode { get; set; }
        public string CEEBName { get; set; }
        public string SchoolTypeCode { get; set; }
        public Nullable<decimal> FormId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Question Question { get; set; }
    }
}
