//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecPersonaSubType
    {
        public RecPersonaSubType()
        {
            this.MemberRecPersonaSubTypes = new HashSet<MemberRecPersonaSubType>();
        }
    
        public int RecPersonaSubTypeId { get; set; }
        public int RecPersonaTypeId { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Updatedby { get; set; }
    
        public virtual ICollection<MemberRecPersonaSubType> MemberRecPersonaSubTypes { get; set; }
    }
}
