//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqGroupDetail
    {
        public decimal ReqGroupDetailId { get; set; }
        public decimal ReqGroupId { get; set; }
        public decimal QuestionId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<int> MemberReqGroupDetailTemplateId { get; set; }
    
        public virtual MemberReqGroupDetailTemplate MemberReqGroupDetailTemplate { get; set; }
        public virtual Question Question { get; set; }
        public virtual ReqGroup ReqGroup { get; set; }
    }
}
