//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqRuleExpression
    {
        public decimal ReqRuleExpressionId { get; set; }
        public decimal ReqRuleId { get; set; }
        public string RelationalOperator { get; set; }
        public decimal QuestionId { get; set; }
        public string Response { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> MemberReqRuleExpTemplateId { get; set; }
        public string ComparisonField { get; set; }
    
        public virtual MemberReqRuleExpTemplate MemberReqRuleExpTemplate { get; set; }
        public virtual Question Question { get; set; }
        public virtual ReqRule ReqRule { get; set; }
    }
}
