//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqRuleTrigger
    {
        public decimal ReqRuleTriggerId { get; set; }
        public decimal ReqRuleId { get; set; }
        public decimal TriggerQuestionId { get; set; }
        public Nullable<int> TargetSectionId { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<int> MemberReqRuleTrgrTemplateId { get; set; }
    
        public virtual MemberReqRuleTrgrTemplate MemberReqRuleTrgrTemplate { get; set; }
        public virtual Question Question { get; set; }
        public virtual ReqRule ReqRule { get; set; }
    }
}
