//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDSConfig
    {
        public SDSConfig()
        {
            this.SDSSchedules = new HashSet<SDSSchedule>();
        }
    
        public int SDSConfigId { get; set; }
        public Nullable<short> ProcessType { get; set; }
        public Nullable<short> FormType { get; set; }
        public Nullable<short> StageType { get; set; }
        public Nullable<short> PoolType { get; set; }
        public Nullable<short> PoolValue { get; set; }
        public Nullable<bool> IsBatch { get; set; }
        public Nullable<short> BatchSize { get; set; }
        public string FTPPath { get; set; }
        public Nullable<bool> KeepInControlCenter { get; set; }
        public Nullable<bool> IsCustomFileName { get; set; }
        public string CustomFileName { get; set; }
        public string PublicKeyFileName { get; set; }
        public Nullable<bool> IncludeWritingSupplement { get; set; }
        public Nullable<bool> IncludeRecommendations { get; set; }
        public Nullable<bool> IncludeSR { get; set; }
        public Nullable<bool> IncludeOR { get; set; }
        public Nullable<bool> IncludeMR { get; set; }
        public Nullable<bool> IncludeFR { get; set; }
        public Nullable<bool> IncludeTE { get; set; }
        public Nullable<bool> IncludeOE { get; set; }
        public Nullable<bool> IncludeRR { get; set; }
        public Nullable<bool> IncludeAE { get; set; }
        public Nullable<bool> IncludeED { get; set; }
        public Nullable<bool> IncludeED2 { get; set; }
        public Nullable<bool> IncludeFW { get; set; }
        public Nullable<bool> EnableBookmark { get; set; }
        public Nullable<bool> EnableDuplexPrinting { get; set; }
        public Nullable<bool> GenerateXmlIndexFile { get; set; }
        public Nullable<bool> IgnorePrintedDate { get; set; }
        public Nullable<bool> MarkAsPrintedExported { get; set; }
        public Nullable<bool> CompressPdf { get; set; }
        public string CompressPdfFileName { get; set; }
        public Nullable<bool> Encrypt { get; set; }
        public Nullable<bool> SeperateTranscript { get; set; }
        public Nullable<int> ExportTemplateId { get; set; }
        public Nullable<bool> CreateEmptyXmlFile { get; set; }
        public Nullable<bool> IncludeHeader { get; set; }
        public Nullable<bool> ExcludeExportedRecords { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<decimal> MemberId { get; set; }
        public bool TestApp { get; set; }
    
        public virtual ExportTemplate ExportTemplate { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<SDSSchedule> SDSSchedules { get; set; }
    }
}
