//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLog
    {
        public int SessionLogId { get; set; }
        public Nullable<decimal> ApplicantId { get; set; }
        public Nullable<decimal> RecommenderId { get; set; }
        public Nullable<int> UserProfileId { get; set; }
        public System.DateTime sessionStartDt { get; set; }
        public Nullable<System.DateTime> sessionEndDt { get; set; }
        public string IPInfo { get; set; }
        public string browser { get; set; }
        public string Server { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<bool> DeleteStatus { get; set; }
    }
}
